"""
Improper Uniform Prior for Unique Random Value Generation.

This module provides a specialized prior distribution class that extends the
ImproperUniform prior from smcpy to generate unique random values using a
custom generator function. It is designed to prevent duplicate values in
sampling scenarios where uniqueness is required.

Constants
---------
MAX_REPEATS : int
    Maximum number of consecutive attempts allowed before warning about
    potential generator issues (default: 100).

Example
-------
>>> def my_generator():
...     return np.random.randint(0, 1000)
>>>
>>> prior = ImproperUniformPrior(my_generator)
>>> samples = prior.rvs(10)  # Generate 10 unique samples
>>> print(samples.shape)
(10, 1)

"""

import warnings
import numpy as np

from smcpy.priors import ImproperUniform

MAX_REPEATS = 100
# After warning, give up and allow duplicates if the pool still hasn't grown
# after this many additional consecutive failures (must be > 2*MAX_REPEATS so
# that slow-but-not-exhausted generators still get a fair chance).
_MAX_STAGNATION = 10 * MAX_REPEATS


class ImproperUniformPrior(ImproperUniform):
    """
    A class that extends ImproperUniform to generate unique random values.

    This prior uses a custom generator function to produce unique random values
    and warns if the generator repeatedly produces duplicates.

    Parameters
    ----------
    generator : callable
        A function that generates random values when called with no arguments.
        This generator should return a hashable type.

    Notes
    -----
    This class tracks duplicate values and warns if the generator fails to
    produce a unique value after a set number of consecutive attempts.
    """

    def __init__(self, generator):
        super().__init__()
        self._generator = generator

    # pylint: disable=W0613
    def rvs(self, N, random_state=None):
        """
        Generate N unique random values using the generator.

        Parameters
        ----------
        N : int
            Number of unique random values to generate.

        Returns
        -------
        ndarray
            Array of shape (N, 1) containing unique values generated by the generator.

        Warns
        -----
        UserWarning
            If the generator fails to produce a new unique value after MAX_REPEATS
            consecutive attempts.

        Notes
        -----
        The random_state parameter is included for compatibility with scipy.stats
        distributions but is not actually used by this method.
        """
        pool = set()
        pool_size = 0
        attempts = 0
        already_warned = False
        while len(pool) < N:
            pool.add(self._generator())

            if len(pool) == pool_size:
                attempts += 1
            else:
                pool_size = len(pool)
                attempts = 0

            if attempts >= MAX_REPEATS and not already_warned:
                warnings.warn(
                    f"Generator called {MAX_REPEATS} times in a row without finding a "
                    "new unique model. This may indicate an issue with the generator "
                    "or insufficient unique models available."
                )
                already_warned = True

            if attempts >= _MAX_STAGNATION:
                # Generator appears exhausted; fill remaining slots with
                # samples drawn (with replacement) from the existing pool.
                pool_list = list(pool)
                while len(pool_list) < N:
                    pool_list.append(pool_list[len(pool_list) % len(pool_list)])
                return np.c_[pool_list]

        return np.c_[list(pool)]

    def logpdf(self, x: np.ndarray) -> np.ndarray:
        """
        Compute log-prior probability for an array of AGraph expressions.

        Parameters
        ----------
        x : array-like
            Array or list of AGraph objects.

        Returns
        -------
        ndarray
            Array of shape ``(N, 1)`` with log-probability values.
        """
        return np.ones((x.shape[0], 1))
